metadata:
  last_updated: '2025-08-02 20:14:20'
  optimization_version: v1.0
  total_params: 20
  description: 策略优化参数配置文件
  method: genetic_algorithm
  timestamp: '2025-08-02T20:14:20.389859'
  param_count: 20
strategy_params:
  rise_threshold: 0.04
  max_days: 20
  final_threshold: 0.35  # 降低阈值，增加信号数量
confidence_weights:
  rsi_oversold_threshold: 25  # 更严格的超卖标准
  rsi_low_threshold: 40
  dynamic_confidence_adjustment: 0.1
  market_sentiment_weight: 0.15
  trend_strength_weight: 0.25  # 从0.15调整
  momentum_reversal_bonus: 0.35  # 新增参数
technical_indicators:
  bb_near_threshold: 1.005  # 更接近布林带下轨
  price_decline_threshold: -0.018
  rsi_oversold_threshold: 25  # 更严格的超卖标准
  rsi_low_threshold: 40
volume_params:
  volume_panic_threshold: 1.8  # 更严格的恐慌标准
  volume_panic_bonus: 0.12
  volume_surge_bonus: 0.06
  volume_shrink_penalty: 0.55  # 从0.68调整
market_params:
  market_sentiment_weight: 0.15
  trend_strength_weight: 0.25  # 从0.15调整
  dynamic_confidence_adjustment: 0.1
strategy_level_params:
  bb_near_threshold: 1.005  # 更接近布林带下轨
  volume_panic_threshold: 1.8  # 更严格的恐慌标准
  volume_surge_threshold: 1.25
  volume_shrink_threshold: 0.78
