ai:
  enable: true
  model_type: machine_learning
  model_save_path: models/ai_model.pkl
  models_dir: models
  optimization_interval: 30
  data_decay_rate: 0.4
  train_test_split_ratio: 0.8
  # 训练数据时间范围配置
  training_data:
    full_train_years: 6           # 完全训练使用6年数据
    optimize_years: 6             # 优化模式使用6年数据
    incremental_years: 1          # 增量训练使用1年数据
    min_years: 5                  # 最小年数限制
    max_years: 12                 # 最大年数限制
    adaptive_range: true          # 是否启用自适应范围调整
  optimization:
    global_iterations: 500
    incremental_iterations: 1000
    incremental_contraction_factor: 0.5
    enable_incremental: true
    enable_history: true
    max_history_records: 100
  advanced_optimization:
    enabled: true
    use_hierarchical: true
    use_scipy: true
    use_time_series_cv: true
  validation:
    train_ratio: 0.65
    validation_ratio: 0.2
    test_ratio: 0.15
    walk_forward:
      enabled: true
      window_size: 252
      step_size: 63
  early_stopping:
    enabled: true
    patience: 50
    min_delta: 0.001
  bayesian_optimization:
    enabled: true
    n_calls: 100
    n_initial_points: 20
    acq_func: EI
    xi: 0.01
    kappa: 1.96
    n_jobs: 1
    random_state: 42
  genetic_algorithm:
    population_size: 20
    generations: 10
    crossover_rate: 0.8
    mutation_rate: 0.1
  scoring:
    success_weight: 0.4
    rise_weight: 0.3
    speed_weight: 0.2
    risk_weight: 0.1
    rise_benchmark: 0.1
    risk_benchmark: 0.2
  optimization_ranges:
    dynamic_confidence_adjustment:
      min: 0.05
      max: 0.25
      step: 0.02
    market_sentiment_weight:
      min: 0.08
      max: 0.25
      step: 0.02
    trend_strength_weight:
      min: 0.06
      max: 0.2
      step: 0.02
    volume_weight:
      min: 0.15
      max: 0.35
      step: 0.02
    price_momentum_weight:
      min: 0.12
      max: 0.3
      step: 0.02
backtest:
  start_date: '2022-01-01'
  end_date: '2025-06-21'
  default_start_date: '2023-01-01'
  default_end_date: '2025-06-21'
  rolling_window: 252
  rolling_step: 63
  generate_charts: true
  charts_dir: charts
data:
  data_file_path: data/SHSE.000905_1d.csv
  data_source: akshare
  index_code: SHSE.000905
  frequency: 1d
  history_days: 1000
  cache_enabled: true
  cache_dir: cache
logging:
  level: INFO
  file: logs/system.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  max_bytes: 10485760
  backup_count: 5
notification:
  methods:
  - console
  - email
  logs_dir: logs
  email:
    sender: quant_system@example.com
    recipients:
    - your_email@example.com
    smtp_server: smtp.example.com
    smtp_port: 587
    username: your_username
    password: your_password
results:
  save_path: results
  save_detailed: true
  images_path: results/images
  tables_path: results/tables
risk:
  min_confidence: 0.6
  max_daily_signals: 3
  cooldown_days: 5
strategy:
  rise_threshold: 0.04
  max_days: 20
  results_dir: results
  bb_period: 20
  bb_std: 2
  rsi_period: 14
  macd_fast: 12
  macd_signal: 9
  macd_slow: 26
  ma_periods:
  - 5
  - 10
  - 20
  - 60
  confidence_weights:
    final_threshold: 0.5
    ma_all_below: 0.3
    ma_partial_below: 0.2
    bb_lower_near: 0.2
    bb_near_threshold: 1.02
    decline_threshold: -0.05
    recent_decline: 0.2
    rsi_low: 0.2
    rsi_low_threshold: 40
    rsi_oversold: 0.3
    rsi_oversold_threshold: 30
    macd_negative: 0.1
    volume_panic_bonus: 0.1
    volume_surge_bonus: 0.05
    volume_shrink_penalty: 0.7
    volume_panic_threshold: 1.4
    volume_surge_threshold: 1.2
    volume_shrink_threshold: 0.8
    price_decline_threshold: -0.02
    dynamic_confidence_adjustment: 0.05
    market_sentiment_weight: 0.16
    trend_strength_weight: 0.16
    volume_weight: 0.25
    price_momentum_weight: 0.2
  scoring:
    success_weight: 0.5
    rise_weight: 0.3
    days_weight: 0.2
    rise_benchmark: 0.1
    days_benchmark: 10.0
system:
  mode: backtest
  log_level: INFO
  log_file: logs/system.log
